DATA SEGMENT
    STR1 DB 1,2,3,4,5,6,7,8,9,10
    STR2 DB 3,4,5,6,7,8,9,10,11,12
    STR3 DB 10 DUP(0)
    CN EQU $-STR3 
DATA ENDS
CODE SEGMENT
	ASSUME CS:CODE,DS:DATA
STA:
    MOV AX,DATA
    MOV DS,AX
    MOV CX,CN
    MOV SI,0
A:  MOV AL,STR1[SI]
    MOV BL,STR2[SI]
    ADD AL,BL	
    MOV STR3[SI],AL
    INC SI
    LOOP A
    MOV AH,4CH
    INT 21H
CODE    ENDS
    END STA
    